spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1994
    url: jdbc:mysql://localhost:3306/redis
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"